project:
  type: website
  output-dir: docs 
website:
  title: "Mohammed Akram Akbar"
  navbar:
    background: "#536878"
    left:
      - href: index.qmd
        text: About
      - href: cv/index.qmd
        text: CV

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true

editor: visual

